services:
  db:
    image: postgres:16-alpine
    container_name: sancocholab_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sancocholab
      POSTGRES_PASSWORD: sancocholab
      POSTGRES_DB: sancocholab
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: sancocholab_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker
    environment:
      NODE_ENV: development
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npx prisma db seed &&
      npm run start:dev
      "

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sancocholab_web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.angular
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sancocholab_pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: johanstian20@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: rmmr
      PGADMIN_DISABLE_POSTFIX: "1"
    ports:
      - "5050:80"

volumes:
  db_data:
    name: sancocholab_db_data

